title: Nicholas Hurry # your name (or website title) here
logo: "/images/logo.png?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  I am Nicholas Hurry, a passionate marketing professional with a strong focus on social media marketing and digital content creation. With a background in marketing, including an Honors Bachelor of Commerce from Ontario Tech University, I have developed a solid skill set in digital marketing, SEO, and data analysis. My hands-on experience with tools such as WordPress, Adobe Creative Suite, and Google Analytics, along with a recent internship optimizing SEO for Consolidated Credit Counseling Services, positions me well for roles in marketing and design. I bring adaptability, a love for learning, and creativity to every project I work on.
  <br><br>
  Second description 
  <br><br>
  <a href="https://www.linkedin.com/in/example/">View My LinkedIn Profile</a> 
  
remote_theme: pages-themes/minimal@v0.2.0
plugins:
- jekyll-remote-theme
google_analytics: UA-000000-0 # your Google Analytics tracking ID here
